add more patching

diff --git a/cygsetup b/cygsetup
--- a/cygsetup
+++ b/cygsetup
@@ -61,6 +61,15 @@ perl -i.bak -pe ' s/(    centos_install_nginx)/\#$1/; s/(    centos_install_node
 perl -i.bak -pe 's/^(boto|vmprof|psutil)/\#$1/' agent/requirements/base.txt
 perl -i.bak -pe 's/^(boto|vmprof|psutil)/\#$1/' client/requirements/base.txt
 perl -i.bak -pe 's/^/\#/ if /(^boto|^vmprof|^sqlalchemy|^cryptography|egg=python-swiftclien|pyOpenSSL|future|psutil)/' starfish/requirements/base.txt
+perl -pe 'if (m/STARFISH_BIN_DIR=/) {printf "    SFHOME=\$(echo \$SFHOME | tr -s %c/%c)\n", 39, 39;}' sf-packaging/packaging-scripts/post-install.sh
+
+# strip off double slashes in paths. Cygwin doesn't like them
+# also comment out generate manpages from install_tgz
+patch -p0 --forward < ../patches/sf-packaging.patch
+if [ $? -ne 0 ]; then
+	echo "patch of sf-packaging installers failed"
+	exit 1
+fi
 
 patch --forward -p0 < ../patches/setup.py.patch
 if [ $? -ne 0 ]; then
@@ -69,7 +78,7 @@ if [ $? -ne 0 ]; then
 fi
 
 # fix base_service.py - disable vmprof
-perl -i.bak -pe 's/^import vmprof/\#/' starfish/src/sfutils/base_service.py
+perl -i.bak -pe '/^import vmprof/^/\#/' starfish/src/sfutils/base_service.py
 
 # turn off wdb
 perl -i.bak -pe 's/^wdb/\#wdb/' starfish/requirements/dev.txt
