fixing sudo and psql setup

diff --git a/ddsetup b/ddsetup
--- a/ddsetup
+++ b/ddsetup
@@ -11,13 +11,21 @@ export DD_API_KEY=6448339284657b30a3c183caf94da0de
 pg_dest=`grep pg_uri /opt/starfish/etc//99-local.ini | awk 'BEGIN {FS="[@/]+"}; {print $3;}'`
 pg_ip=`echo $pg_dest | awk -F: '{print $1}'`
 pg_port=`echo $pg_dest | awk -F: '{print $2}'`
+pg_pass=`grep pg_uri /opt/starfish/etc//99-local.ini | awk 'BEGIN {FS="[@:]+"}; {print $3;}'`
 
+
+uid=`id -u`
+if [[ $uid  != 0 ]]; then
+  echo "This script needs root permissions to install packages and"
+  echo "configure system services. Run as root or with sudo -H "
+  exit 1
+fi
 
 if [ $# -ne 1 ]; then
-	echo "error: must include site name as argument"
-	exit 1
+  echo "error: must include site name as argument"
+  exit 1
 else
-	site=$1
+  site=$1
 fi
 echo "Installing use site name '$site'"
 
@@ -58,7 +66,7 @@ if [ -f /etc/redhat-release ]; then
   if [[ $ddversion =~ "datadog-agent-5" ]]; then
     echo "upgrading datadog-agent"
     mv /etc/dd-agent /etc/dd-agent.old
-    sudo rpm -e datadog-agent
+    rpm -e datadog-agent
     bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)"
   fi
   # check/fix global tags
@@ -165,8 +173,15 @@ cnt=$(grep -c datadog /root/.pgpass 2>&1)
 if [ ! -f /root/.pgpass -o "$cnt" = "0" ]; then
   echo "${pg_dest}:postgres:datadog:X83FGVReB5DJmbCSIShu1x8L" >> /root/.pgpass
   chmod 600 /root/.pgpass
-  sudo -u postgres psql -qc "create user datadog with password 'X83FGVReB5DJmbCSIShu1x8L';
+  if [[ $uid == 0 ]]; then
+    # make and use a .pgpass entry
+    echo "${pg_dest}:postgres:starfish:$pg_pass" >> /root/.pgpass
+    psql -w starfish -h $pg_dest -d postgres -qc "create user datadog with password \'X83FGVReB5DJmbCSIShu1x8L\';
 grant SELECT ON pg_stat_database to datadog;" 
+  else
+    sudo -u postgres psql -qc "create user datadog with password 'X83FGVReB5DJmbCSIShu1x8L';
+grant SELECT ON pg_stat_database to datadog;" 
+  fi
   # try to check the DB
   psql -w datadog -h $pg_ip -p $pg_port -d postgres -c "select * from pg_stat_database LIMIT(1);"  \
   && echo -e "\e[0;32mPostgres connection - OK\e[0m"  || \
